#!/usr/bin/env python3
"""Configure Android signing in build.gradle generated by Expo prebuild.
This script is IDEMPOTENT - safe to run multiple times.
"""
import sys

GRADLE_PATH = 'mobile/android/app/build.gradle'

with open(GRADLE_PATH) as f:
    content = f.read()

# 1. Add release signingConfig in signingConfigs block (after debug block)
old_signing = (
    "    signingConfigs {\n"
    "        debug {\n"
    "            storeFile file('debug.keystore')\n"
    "            storePassword 'android'\n"
    "            keyAlias 'androiddebugkey'\n"
    "            keyPassword 'android'\n"
    "        }\n"
    "    }"
)
new_signing = (
    "    signingConfigs {\n"
    "        debug {\n"
    "            storeFile file('debug.keystore')\n"
    "            storePassword 'android'\n"
    "            keyAlias 'androiddebugkey'\n"
    "            keyPassword 'android'\n"
    "        }\n"
    "        release {\n"
    "            storeFile file('fridr.keystore')\n"
    "            storePassword 'fridr2026!'\n"
    "            keyAlias 'fridr'\n"
    "            keyPassword 'fridr2026!'\n"
    "        }\n"
    "    }"
)

if old_signing in content:
    content = content.replace(old_signing, new_signing)
    print('[OK] Added release signing config')
elif 'fridr.keystore' in content:
    print('[OK] Release signing config already present')
else:
    print('[ERROR] Could not find signingConfigs debug block!')
    print('First 100 chars:', content[:100])
    sys.exit(1)

# 2. Change signingConfigs.debug to signingConfigs.release in the release buildType
old_release = (
    "        release {\n"
    "            // Caution! In production, you need to generate your own keystore file.\n"
    "            // see https://reactnative.dev/docs/signed-apk-android.\n"
    "            signingConfig signingConfigs.debug"
)
new_release = (
    "        release {\n"
    "            signingConfig signingConfigs.release"
)

if old_release in content:
    content = content.replace(old_release, new_release)
    print('[OK] Set release signingConfig to signingConfigs.release')
elif 'signingConfig signingConfigs.release' in content:
    print('[OK] Release signingConfig already correct')
else:
    print('[ERROR] Could not find release buildType signingConfig!')
    sys.exit(1)

with open(GRADLE_PATH, 'w') as f:
    f.write(content)

print('[OK] Signing configured successfully!')
